namespace NetCore.Utils
{
    public static class Enums
    {
        public enum ErrorCode
        {
            //tài xỉu
            ERR_NOTBET_MULTILOCATION = -208,
            ERR_BETVALUE_INVALID = -212,
            ERR_BETTIME_EXPIRED = -207,
            ERR_NOT_PERMISSTION = -209,
            ERR_MAX_BET = -210,
            ERR_MAX_BET_USER = -211,
            ERR_MIN_BET_USER = -213,
            ERR_NOT_ENOUGH_MONEY = -51,
            ERR_AUTOBET_OUTOFQUANTITY = -278, // Auto 2 lần trong 1 phiên
            ERR_AUTOBET_OUTOFSESSION = -279, // Phiên chọn đã qua rồi
            ERR_BETTINGDATA_INVALID = -232,
            ERR_BETTING_TOOFAST = -271,
            ERR_IS_AGENCY = -272,

            //slot
            BonusNull = -1003,
            X2Null = -1004,
            FreeNull = -1005,
            Success = 1,
            Exception = -99,
            NotAuthen = -403,
            PlayerNull = -1002,
            DuplicateSpin = -10003,
            InvalidBalance = -10004,
            NotEnoughMoney = -51,
            NotEnoughMoneyToMuch = -10051,
            Failed = -1,
            DuplicatePlayer = -1006,
        }

        public enum GameType
        {
            NORMAL = 0,
            BONUS = 3,
            FREESPIN = 1,
            X2GAME = 2
        }

        public enum CAPTCHATYPE
        {
            MATH = 0,
            STRING = 1,
            TOKEN = 2,
            SESSION = 3
        }

        public enum ErrorCodes
        {
            SUCCESS = 0,
            SERVER_ERROR = 1000,
            SERVER_MAINTAIN = 1001,
            ACCOUNT_NAME_INVALID = 1002,
            PASSWORD_INVALID = 1003,
            NICKNAME_INVALID = 1004,
            DATA_IS_NULL = 1005,
            REGISTER_ACCOUNT_ERROR = 1006,
            ACCOUNT_EXIST = 1007,
            NICKNAME_EXIST = 1008,
            PLATFORM_INVALID = 1009,
            CAPTCHA_INVALID = 1010,
            LOGIN_ERROR = 1011,
            ACCOUNT_BLOCKED = 1012,
            ACCOUNT_NOT_EXIST = 1013,
            NEED_OTP_CODE = 1014,
            TOKEN_ERROR = 1015,
            VALIDATE_ERROR = 1016,
            ACCOUNT_DISABLED = 1017,
            FACEBOOK_INVALID = 1018,
            NOT_AUTHEN = 1019,
            INPUT_PARAM_ERROR = 1020,
            IDENTITY_CODE_INVALID = 1021,
            INPUT_OTP_CODE = 1022,
            FORBIDDEN_ACCESS = 1023,
            MOBILE_NUMBER_INVALID = 1024,
            MOBILE_NUMBER_ALREADY_REGISTER = 1025,
            ACCOUNT_UPDATE_FAILED = 1026,
            PASSWORD_NEW_NOT_MATCH = 1027,
            PASSWORD_OLD_INVALID = 1028,
            PASSWORD_NEW_INVALID = 1029,
            ACCOUNT_OTP_NOT_REGISTER = 1030,
            ACCOUNT_CHANGE_PASSWORD_FAILED = 1031,
            ACCOUNT_EMAIL_INVALID = 1032,
            ACCOUNT_EMAIL_CURRENT_INVALID = 1033,
            ACCOUNT_EMAIL_UPDATE_FAILED = 1034,
            ACCOUNT_EMAIL_UPDATE_SUCCESS = 1035,
            ACCOUNT_VERIFY_CODE_INVALID = 1036,
            GIFT_CODE_INVALID = 1037,
            ACCOUNT_NOT_LOGGED_IN = 1038,
            ACCOUNT_OTP_DATA_NOT_MATCH = 1039,
            ACCOUNT_RESET_PASSWORD_FAILED = 1040,
            ACCOUNT_RESET_PASSWORD_SUCCESS = 1041,
            SYSTEM_BUSY = 1042,
            ACCOUNT_CHARACTER_NAME_UPDATED = 1043,
            ACCOUNT_CHARACTER_NAME_INVALID = 1044,
            ACCOUNT_CHARACTER_NAME_MUST_DEFFENT_ACCNAME = 1045,
            ACCOUNT_CHARACTER_NAME_UPDATE_FAILED = 1046,
            SYSTEM_ERROR = 1047,
            ACCOUNT_ALREADY_REGISTER_OTP = 1048,
            ACCOUNT_REGISTER_OTP_FAILED = 1049,
            ACCOUNT_MOBILE_NOT_MATCH = 1050,
            ACCOUNT_SERCURE_CODE_INVALID = 1051,
            ACCOUNT_OTP_CANCEL_FAILED = 1052,
            ACCOUNT_CAN_NOT_EXC_FUNCTION = 1053,
            ACCOUNT_MOBILE_CURRENT_INVALID = 1054,
            ACCOUNT_MOBILE_NEW_MUST_DIFF = 1055,
            ACCOUNT_MOBILE_NEW_ALREADY_USED = 1056,
            ACCOUNT_MOBILE_ALREADY_USED = 1057,
            ACCOUNT_MOBILE_NEW_INVALID = 1058,
            ACCOUNT_MOBILE_NEW_NOT_MATCH = 1059,
            ACCOUNT_OTP_INVALID = 1060,
            ACCOUNT_MOBILE_UPDATE_FAILED = 1061,
            TOTAL_COIN_MUST_GREATER_THAN_0 = 1062,
            ACCOUNT_OTP_NOT_REGISTER_YET = 1063,
            ACCOUNT_MISSING_MOBILE = 1064,
            ACCOUNT_OTP_NOT_MATCH = 1065,
            ACCOUNT_SERCURE_ACTIVE_FAILED = 1066,
            ACCOUNT_MISSING_EMAIL = 1067,
            TOTAL_COIN_MIN_FREEZE_NOT_ENOUGH = 1068,
            DATA_INVALID = 1069,
            TRANSACTION_FAILED = 1070,
            COIN_FREEZE_FAILED = 1071,
            ACCOUNT_MOBILE_INVALID = 1072,
            VIP_POINT_INVALID = 1073,
            ACCOUNT_MOBILE_NOT_ENOUGH_24H = 1074,
            AGENCY_NAME_INVALID = 1075,
            AGENCY_REGISTER_SUCCESS = 1076,
            AGENCY_REGISTER_FAILED = 1077,
            AGENCY_ID_INVALID = 1078,
            TRANSACTION_EXPIRED = 1079,
            ACCOUNT_OTP_EXPIRED = 1080,
            FUNCTION_LOCKED = 1081,
            VERIFY_CODE_NULL = 1082,
            VERIFY_CODE_INVALID = 1083,
            TOTAL_COIN_INVALID = 1084,
            XU_TOPUP_FAILED = 1085,
            PROVIDER_INVALID = 1086,
            PRICE_INVALID = 1087,
            PAYMENT_TYPE_INVALID = 1088,
            ACCOUNT_BALANCE_NOT_ENOUGH = 1089,
            CAN_NOT_TRANSFER_TO_YOURSELF = 1090,
            BON_VALUE_INVALID = 1091,
            SEND_ACCOUNT_NOT_EXIST = 1092,
            NICK_NAME_SEND_NOT_MATCH = 1093,
            RECEIVER_ACCOUNT_NOT_EXIST = 1094,
            TRANSFER_COIN_FAILED = 1095,
            IAP_TOPUP_SUCCESS = 1096,
            PROFILE_NOT_FOUND = 1097,
            LEADER_BOARD_NOT_FOUND = 1098,
            ROOM_VALUE_INVALID = 1099
        }
    }
}